const API_BASE_URL_DEVELOPMENT = "https://localhost:7001";
const API_BASE_URL_PRODUCTION = "https://efcoreapi.azurewebsites.net";

const ENDPOINTS = {
  GET_ALL_PEOPLE: "api/people",
  GET_PERSON_BY_ID: "api/people",
  CREATE_PERSON: "api/people",
  UPDATE_PERSON: "api/people",
  DELETE_PERSON: "api/people",
  LOGIN: "api/login",
};

const development = {
  API_URL_GET_ALL_PEOPLE: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_ALL_PEOPLE}`,
  API_URL_GET_PERSON_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.GET_PERSON_BY_ID}`,
  API_URL_CREATE_PERSON: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.CREATE_PERSON}`,
  API_URL_UPDATE_PERSON: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.UPDATE_PERSON}`,
  API_URL_DELETE_PERSON: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.DELETE_PERSON}`,
  API_URL_LOGIN: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS.LOGIN}`,
};

const production = {
  API_URL_GET_ALL_PEOPLE: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_ALL_PEOPLE}`,
  API_URL_GET_PERSON_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.GET_PERSON_BY_ID}`,
  API_URL_CREATE_PERSON: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.CREATE_PERSON}`,
  API_URL_UPDATE_PERSON: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.UPDATE_PERSON}`,
  API_URL_DELETE_PERSON: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.DELETE_PERSON}`,
  API_URL_LOGIN: `${API_BASE_URL_PRODUCTION}/${ENDPOINTS.LOGIN}`,
};

const Constants = process.env.NODE_ENV === "development" ? development : production;

export default Constants;
